<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Plans_datum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get plans_datum by plan_id
     */
    function get_plans_datum($plan_id)
    {
        return $this->db->get_where('plans_data',array('plan_id'=>$plan_id))->row_array();
    }

    /*
     * Get all plans_data
     */
    function get_all_plans_data($params = null)
    {
      //en caso de que reciba parametros
      if(isset($params) && !empty($params))
      {
          $this->db->where($params);
      }
        $this->db->order_by('plan_id', 'desc');
        return $this->db->get('plans_data')->result_array();
    }

    /*
     * function to add new plans_datum
     */
    function add_plans_datum($params)
    {
        $this->db->insert('plans_data',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update plans_datum
     */
    function update_plans_datum($plan_id,$params)
    {
        $this->db->where('plan_id',$plan_id);
        return $this->db->update('plans_data',$params);
    }

    /*
     * function to delete plans_datum
     */
    function delete_plans_datum($plan_id)
    {
        return $this->db->delete('plans_data',array('plan_id'=>$plan_id));
    }
}
