<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Products_sale_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }



    function sum_ingresos($params =  null, $products_sales_id = null){
      if(isset($params) && !empty($params))
      {
          $this->db->where($params);
      }
      if(isset($products_sales_id) && !empty($products_sales_id))
      {
          $this->db->where_in('products_sales_code', $products_sales_id);
      }
      $this->db->join('products_data', 'products_data.product_id = products_sales.products_sales_code');
      $this->db->select_sum('products_sales_amount');
      $this->db->select('product_name, COUNT(products_sales_amount) AS Cantidad, product_cost AS CostoUnitario, product_cost_sale AS CostoUnitarioVenta');
      $this->db->group_by('products_sales_code');

        return $this->db->get('products_sales')->result_array();

    }



    /*
     * Get products_sale by products_sales_id
     */
    function get_products_sale($products_sales_id)
    {
        return $this->db->get_where('products_sales',array('products_sales_id'=>$products_sales_id))->row_array();
    }

    function get_daily_sales(){

      $this->db->select('SUM(products_sales_amount) AS amount', FALSE);
      $this->db->where(array('DATE(products_sales_date)' => date($this->config->item('query_date'))));
      return $this->db->get('products_sales')->row_array();

    }

    /*
     * Get all products_sales
     */
    function get_all_products_sales($params = null)
    {
      if(isset($params) && !empty($params))
      {
          $this->db->where($params);
      }
      $this->db->join('users', 'products_sales.products_sales_user_id = users.id');
      //$this->db->join('products_data', 'products_sales.products_sales_code = products_data.product_id');
        $this->db->order_by('products_sales_id', 'desc');
        return $this->db->get('products_sales')->result_array();
    }

    /*
     * function to add new products_sale
     */
    function add_products_sale($params)
    {
        $this->db->insert('products_sales',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update products_sale
     */
    function update_products_sale($products_sales_id,$params)
    {
        $this->db->where('products_sales_id',$products_sales_id);
        return $this->db->update('products_sales',$params);
    }

    /*
     * function to delete products_sale
     */
    function delete_products_sale($products_sales_id)
    {
        return $this->db->delete('products_sales',array('products_sales_id'=>$products_sales_id));
    }
}
