<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Reportes extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        $this->data = $this->generales->imports_generales();
        $this->load->library('form_validation');
        $this->data['active'] = 'Reportes';


        $this->load->model('Products_datum_model');
        $this->load->model('Products_sale_model');
        $this->load->model('Customer_entry_model');
        $this->load->model('Payments_datum_model');


                if($this->ion_auth->in_group(0)){
                  $this->session->set_flashdata('error', 'No tiene permisos para realizar esta accion');
                  redirect('/');
                }

      }
      public function index(){
        $this->data['_view'] = 'reportes/index';
        $this->load->view('layouts/main',$this->data);

      }


      public function export_ingresos($params){
            $this->load->dbutil();
            $this->load->helper('file');
            $this->load->helper('download');
            $query = $this->Customer_entry_model->get_all_customer_entry(array('DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));

            $delimiter = ",";
            $newline = "\r\n";
            $data = $this->dbutil->csv_from_result($query, $delimiter, $newline);
            force_download('CSV_Report.csv', $data);
      }


      public function Ingresos(){

        // $this->form_validation->set_rules('query_class','Clase','required');
        // $this->form_validation->set_rules('query_date','Dia de la semana','required');
        $this->form_validation->set_rules('query_time','Periodo de Busqueda','required');

        if($this->form_validation->run())
            {

              $this->data['query_time'] = $this->input->post('query_time');
              $dates = explode(' - ', $this->input->post('query_time'));

              echo $this->input->post('query_date');
              echo $this->input->post('query_class');
              if($this->input->post('query_date') == '00'){
                $this->data['lun'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 0, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
                $this->data['mar'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 1, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
                $this->data['mie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 2, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
                $this->data['jue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 3, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
                $this->data['vie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 4, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
                $this->data['sab'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 5, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              }else{

              }

              $this->data['lun'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 0, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['mar'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 1, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['mie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 2, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['jue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 3, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['vie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 4, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['sab'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 5, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              //POR CLASE, es negreada pero bueno
              $this->data['ocho'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 8, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['nueve'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 9, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['diez'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 10, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['once'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 11, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['doce'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 12, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['trece'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 13, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['cat'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 14, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['qui'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 15, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['deci'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 16, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['decisei'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 17, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['decioch'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 18, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['decinue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 19, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['vein'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 20, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['veintiuno'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 21, 'DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $this->data['all_entry'] = $this->Customer_entry_model->get_all_customer_entry(array('DATE(customer_entry_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(customer_entry_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));

            }else{
              echo validation_errors();
              $this->data['lun'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 0));
              $this->data['mar'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 1));
              $this->data['mie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 2));
              $this->data['jue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 3));
              $this->data['vie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 4));
              $this->data['sab'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 5));
      //POR CLASE, es negreada pero bueno
              $this->data['ocho'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 8));
              $this->data['nueve'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 9));
              $this->data['diez'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 10));
              $this->data['once'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 11));
              $this->data['doce'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 12));
              $this->data['trece'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 13));
              $this->data['cat'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 14));
              $this->data['qui'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 15));
              $this->data['deci'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 16));
              $this->data['decisei'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 17));
              $this->data['decioch'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 18));
              $this->data['decinue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 19));
              $this->data['vein'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 20));
              $this->data['veintiuno'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 21));
              $this->data['all_entry'] = $this->Customer_entry_model->get_all_customer_entry();
            }


        $this->data['_view'] = 'reportes/ingresos';
        $this->load->view('layouts/main',$this->data);

      }
      public function Pagos(){
        $this->load->model('Plans_datum_model');
        $this->data['all_plans_data'] = $this->Plans_datum_model->get_all_plans_data();

        $this->form_validation->set_rules('customer_id_plan[]','Plan','required');
        $this->form_validation->set_rules('payment_date','Fecha','required');
        if($this->form_validation->run())
            {

              $this->data['date'] = $this->input->post('payment_date');
              $dates = explode(' - ', $this->input->post('payment_date'));
              $this->data['plans_data'] = $this->input->post('customer_id_plan[]');

              $datos = $this->Payments_datum_model->sum_ingresos(array('DATE(payment_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(payment_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))),$this->input->post('customer_id_plan[]'));
              $this->data['datos'] = json_encode($datos);
              $this->data['tabla'] = $datos;

            }else{
              $datos = $this->Payments_datum_model->sum_ingresos();
              $this->data['datos'] = json_encode($datos);
              $this->data['tabla'] = $datos;
            }


        $this->data['_view'] = 'reportes/pagos';
        $this->load->view('layouts/main',$this->data);
      }

      public function Ventas(){

        $this->load->model('Products_datum_model');
        $this->data['products_data'] = $this->Products_datum_model->get_all_products_data();
        $this->form_validation->set_rules('products_sales_date','Fecha','required');
        $this->form_validation->set_rules('product_id[]','Productos','required');

        if($this->form_validation->run())
            {

              $this->data['date'] = $this->input->post('products_sales_date');
              $dates = explode(' - ', $this->input->post('products_sales_date'));
              $this->data['product_id'] = $this->input->post('product_id[]');

              $datos = $this->Products_sale_model->sum_ingresos(array('DATE(products_sales_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(products_sales_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))),$this->input->post('product_id[]'));
              $this->data['datos'] = json_encode($datos);
              $this->data['tabla'] = $datos;
            }else{

              $datos = $this->Products_sale_model->sum_ingresos(array('products_sales_status'=>$this->config->item('Activo')));
              $this->data['datos'] = json_encode($datos);
              $this->data['tabla'] = $datos;
            }

            $this->data['_view'] = 'reportes/ventas';
            $this->load->view('layouts/main',$this->data);

      }

      public function Totales(){

        $this->form_validation->set_rules('products_sales_date','Fecha','required');

        if($this->form_validation->run())
            {
              $this->data['date'] = $this->input->post('products_sales_date');
              $dates = explode(' - ', $this->input->post('products_sales_date'));

              $productos = $this->Products_sale_model->sum_ingresos(array('DATE(products_sales_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(products_sales_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));
              $ventas = $this->Payments_datum_model->sum_ingresos(array('DATE(payment_date) >='=>date($this->config->item('query_date'), strtotime($dates[0])),'DATE(payment_date) <='=>date($this->config->item('query_date'), strtotime($dates[1]))));


            }else{
              $productos = $this->Products_sale_model->sum_ingresos(array('products_sales_status'=>$this->config->item('Activo')));
              $ventas = $this->Payments_datum_model->sum_ingresos();

            }
          $this->data['tabla'] = $productos;
          $this->data['tabla2'] = $ventas;
          $this->data['_view'] = 'reportes/totales';
          $this->load->view('layouts/main',$this->data);
      }




}
