<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Products_datum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get products_datum by product_id
     */
    function get_products_datum($product_id)
    {
        return $this->db->get_where('products_data',array('product_id'=>$product_id))->row_array();
    }

    function Count_prodcucts($params = null){

      if(isset($params) && !empty($params))
      {
          $this->db->where($params);
      }
      $this->db->from('products_data');
      return $this->db->count_all_results();

    }

    function UpdateStock($product_id){
      $this->db->set('product_stock', 'product_stock-1', false);
      $this->db->where('product_id', $product_id);
      return $this->db->update('products_data');
    }

    /*
     * Get all products_data
     */
    function get_all_products_data($params = null)
    {
      if(isset($params) && !empty($params))
      {
          $this->db->where($params);
      }
        $this->db->order_by('product_id', 'desc');
        return $this->db->get('products_data')->result_array();
    }

    /*
     * function to add new products_datum
     */
    function add_products_datum($params)
    {
        $this->db->insert('products_data',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update products_datum
     */
    function update_products_datum($product_id,$params)
    {
        $this->db->where('product_id',$product_id);
        return $this->db->update('products_data',$params);
    }

    /*
     * function to delete products_datum
     */
    function delete_products_datum($product_id)
    {
        return $this->db->delete('products_data',array('product_id'=>$product_id));
    }
}
