<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Reportes extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        $this->data = $this->generales->imports_generales();
        $this->load->library('form_validation');
        $this->data['active'] = 'Reportes';


        $this->load->model('Products_datum_model');
        $this->load->model('Products_sale_model');
        $this->load->model('Customer_entry_model');

      }
      public function index(){
        $this->data['_view'] = 'reportes/index';
        $this->load->view('layouts/main',$this->data);

      }


      public function Ingresos(){
        $this->data['lun'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 0));
        $this->data['mar'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 1));
        $this->data['mie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 2));
        $this->data['jue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 3));
        $this->data['vie'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 4));
        $this->data['sab'] = $this->Customer_entry_model->get_all_customer_entry_count(array('WEEKDAY(customer_entry_date)' => 5));


//POR CLASE, es negreada pero bueno
        $this->data['ocho'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 8));
        $this->data['nueve'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 9));
        $this->data['diez'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 10));
        $this->data['once'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 11));
        $this->data['doce'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 12));
        $this->data['trece'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 13));

        $this->data['cat'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 14));
        $this->data['qui'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 15));
        $this->data['deci'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 16));
        $this->data['decisei'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 17));
        $this->data['decioch'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 18));
        $this->data['decinue'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 19));

        $this->data['vein'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 20));
        $this->data['veintiuno'] = $this->Customer_entry_model->get_all_customer_entry_count(array('customer_entry_class' => 21));


        $this->data['_view'] = 'reportes/ingresos';
        $this->load->view('layouts/main',$this->data);

      }




}
